name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: npm run lint
      - run: npm run build
      - name: Build docs
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/develop')
        run: npm run docs
        # We expect to see syntax errors from the old jsdoc cli not understanding some of our syntax
        # It will still generate what it can, so it's safe to ignore the error
        continue-on-error: true
      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/develop')
        uses: actions/upload-artifact@v4
        with:
          name: playground
          path: ./playground/
      - name: Upload pages artifact
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/develop')
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./playground/

  deploy:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/develop')
    concurrency:
      group: "deploy"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: playground
          path: ./playground
      - name: Deploy to develop-builds branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playground
          publish_branch: develop-builds
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
